services:
  postgres:
    image: postgres:17
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: love
      POSTGRES_DB: snowflake
    ports:
      - '1234:5432'
    volumes:
      - './db/:/docker-entrypoint-initdb.d/'
      - './BigDataSnowflake/data:/data'
      - './script:/script'
    command: >
      -c work_mem=256MB
      -c maintenance_work_mem=256MB
      -c max_wal_size=1GB